### ISSUE TITLE
Use SVG Flags

### ISSUE THREAD

**Issue by 1letter** [plone/plone.i18n#35]
We should use svg icons for the country flags.

**Comment by 1letter** [comment]
Have anyone a opinion to use [this repro](https://github.com/hampusborgos/country-flags) for svg flag. iwould replace all gifs with svg format.

**Comment by agitator** [comment]
Looks like they are not as unified as we would want them, `viewBox`for example ist quite different between individual svgs.
Also looked around but haven't found something good yet

**Comment by 1letter** [comment]
it's a little bit of work and diligence to correct the svg files. i would do that work. I think all viewports should be in the 3:2 format.  But what speak against to use this repro as base (perhaps only the svg files)? I don't have an overview of copyright of the flags until now.  I would use the country flags as inline svg, like the icons in the plone controlpanel.

**Comment by agitator** [comment]
Don't have a strong opinion on which one to use, was just a quick look ;-)
Found these https://github.com/joielechong/iso-country-flags-svg-collection or https://github.com/hampusborgos/country-flags (has an npm package)

The flags should use the icon-resolver and be registered in staticresources.
Bootstrap icons are added there as a dependency which made me look at https://www.npmjs.com/search?q=country-flag
Would be even less work if we could use on of those packages...

**Comment by 1letter** [comment]
Amazing! we have a iconresolver, i see it the first time in action. incredible!

**Comment by 1letter** [comment]
I have open an issue in [plone.staticresources](https://github.com/plone/plone.staticresources/issues/140)

**Comment by agitator** [comment]
Example for the use of the icon resolver is in https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/browser/templates/test_rendering.pt#L49

**Comment by mauritsvanrees** [comment]
I think this has been finished for a while and can be closed.  I have just now removed the branch that belonged to the closed PR #36 which was superseded by #42 which adds SVG flag support.
Thanks all!
