### ISSUE TITLE
Installation still requires `plone.supermodel`

### ISSUE THREAD

**Issue by sallner** [plone/plone.i18n#49]
When I try to install the current version `5.0.0` it does not install `plone.supermodel` along with it as it was removed as dependency in https://github.com/plone/plone.i18n/commit/bbfc4673511cbef7d011dfba5e280206c654cda1 but it is clearly still used in https://github.com/plone/plone.i18n/blob/1f9e36fffd6978e511af1164d2a7240861b93738/plone/i18n/interfaces.py#L1

Can the `model` import be imported from somewhere else now, or should we add `plone.supermodel` as dependency again?

**Comment by mauritsvanrees** [comment]
I think `plone.supermodel` should indeed be added as dependency again.  cc @jensens who removed it, in case he has a different idea.

@sallner Are you up for creating a PR?

**Comment by mauritsvanrees** [comment]
cc @gforcada in case he is already working on a PR that touches this package.  I expect that `z3c.dependencychecker` will find this problem too. :-)

**Comment by jensens** [comment]
Indeed it is imported.
